### ISSUE TITLE
add JsonRenderer as a new OutputRenderer

### ISSUE THREAD

**Issue by dabutvin** [amzn/tiny-attribution-generator#4]
The thinking is that this would be used to facilitate some kind of chaining across different toolsets and make it easier to merge datasets together as opposed to using the Text or HTML renderer

The renderer would do very little, but would produce a format that could be fed back into the generator.

**Comment by jpeddicord** [comment]
Heh, that's clever. Hadn't thought of doing it that way, but it makes sense. Would be useful for archiving attribution data.
