### ISSUE TITLE
Integrate ClearlyDefined into the DocBuilder

### ISSUE THREAD

**Issue by dabutvin** [amzn/tiny-attribution-generator#5]
Right now if there is no license text provided, we [fall back](https://github.com/amzn/tiny-attribution-generator/blob/master/docbuilder.ts#L32-L39) to the spdx canonical license.

Before we fall back to canonical, we could try and fetch license text from [ClearlyDefined](https://clearlydefined.io/) If there is still no match, we would fall back to spdx canonical.

**Comment by jpeddicord** [comment]
Agreed. I think this fits into a broader (somewhat unexplored) picture of how this connects with ClearlyDefined. Most likely we'd try to get that text from CD if that particular component was somehow flagged as having been from CD, or was very easy to identify. Maybe some kind of 2nd-stage pass before generation that tries to link components together.
